apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-server
spec:
  template:
    spec:
      containers:
      - name: event-server
        image: images.home.mtaylor.io/event-server
        ports:
        - name: http
          protocol: TCP
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 8080
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: 8080
