commonLabels:
  app: event-service
resources:
- deployment.yml
- service.yml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: images.home.mtaylor.io/event-server
  newTag: 0.0.11
