apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: event-server
spec:
  selector:
    matchLabels:
      app: event-service
  endpoints:
  - port: http-monitoring
    interval: 15s
